### ISSUE TITLE
Epic 1. Create the project & Set up the Environment

### ISSUE THREAD

**Issue by SerraKD** [SerraKD/cine-frights#1]
Epic Description : Set up the project repository and manage the Heroku deployment.

Tasks:

- [x]  Create the project repository on Gitpod.
- [x] Create a basic working Django web app.
- [x] Deploy project to heroku.
