### ISSUE TITLE
Epic 3. Admin panel & functions

### ISSUE THREAD

**Issue by SerraKD** [SerraKD/cine-frights#15]
Epic Description : Site admins competence & tasks.

Acceptance Criteria as admin:
1.  Create, read, update and delete posts to manage content on the site.
2.  Create draft posts to I finish creating a movie post later on.
3.  Give movies ratings.
4.  Approve or disapprove comments to control what will be visible to other users.
5.  Review and accept movie recommendation forms filled by logged in users.

Tasks:
- [x] Create the admin panel.
- [x] CRUD 
- [x] creating drafts
- [x] ratings
- [x] comment approval
- [x] review movie recommandations
- [x] Test out the all functions as admin.

**Comment by SerraKD** [comment]
Created superuser

**Comment by SerraKD** [comment]
Created first movie post

**Comment by SerraKD** [comment]
Installed and wire up django-summernote for admin panel
