### ISSUE TITLE
 Epic 4. Validation & Testing

### ISSUE THREAD

**Issue by SerraKD** [SerraKD/cine-frights#16]
Epic Description : All testing and validation required for the project.

Tasks:
- [x] Do manual testing. 
- [x] Validate html files with W3C HTML validation.
- [x] Validate css files with W3C CSS  validation.
- [x] Validate python files with PEP8 validation.
- [x]  Validate Js files with JS Lint.
