### ISSUE TITLE
Epic 2. Create Database & Models

### ISSUE THREAD

**Issue by SerraKD** [SerraKD/cine-frights#2]
Epic Description :  configure database, manage environment variables, create models.

Tasks:
- [x]  Create cloud-based database and wire it to the project.
- [x] Determine the database schema and create the models required for project.
- [x]  Make migrations for all models.

**Comment by SerraKD** [comment]
Created basic model for Movie posts, registered in admin.py

**Comment by SerraKD** [comment]
Created basic model for Comments, registered in admin.py.  User rating  will be stars in views
